### ISSUE TITLE
BAD Camera Interface 

### ISSUE THREAD

**Issue by tribeiro** [astroufsc/chimera#90]
The camera interface was messed up somehow. 

https://github.com/astroufsc/chimera/blob/master/src/chimera/interfaces/camera.py#L107-L112

A LOT went down with this modification! Please roll back URGENTLY!!!!!

    __config__ = {"device": "USB",
                  "ccd": CCD.IMAGING,
                  "temp_delta": 2.0,

                  "ccd_saturation_level": 60000,

                  "camera_model": "Fake camera Inc.",
                  "ccd_model": "KAF XYZ 10",
                  "telescope_focal_length": 4000  # milimeter

}

**Comment by wschoenell** [comment]
The problem was introduced on astroufsc/chimera#66. The error was because I did a mistake when I thought that the configuration keywords on chimera are free to append even when they are not specified on the `__config__` variable of the object.

To fix that, I re-added the missing configuration parameters with default value set to `None` and fixed how the `None` is treated where needed. Also, I added `NoneType` variables support to the configuration file. PR will follow in minutes.

**Comment by wschoenell** [comment]
@tribeiro: Did you checked #91? Can we merge it and close this issue?

**Comment by tribeiro** [comment]
Yes please!

Em segunda-feira, 27 de julho de 2015, William Schoenell <
notifications@github.com> escreveu:

> @tribeiro <https://github.com/tribeiro>: Did you checked #91
> <https://github.com/astroufsc/chimera/pull/91>? Can we merge it and close
> this issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/astroufsc/chimera/issues/90#issuecomment-125200395>.
>


-- 
Sent from Mobile

**Comment by wschoenell** [comment]
Fixed #90 by merging #91.
